### PR TITLE
Mobile header adjustments

### PR DESCRIPTION
**Pull request by rburkey87**
Adjusted mobile header site title to wrap for longer content.

### CODE REVIEW

**Comment by kebowdog** [comment]
I just tested this and the first line of the header seems to be indented more than the second line:

image

**Comment by rburkey87** [comment]
Yikes! Not sure why, but I'll check it in the morning. Thank you!

Rebecca

**Comment by rburkey87** [comment]
okay, I fixed it. I'll create a pull request for the fix.

**Comment by rburkey87** [comment]
Okay, I THINK this is completely fixed now. Can somebody review it?

**Pull request merged**
