### PR TITLE
Group Assignment Dec 8 to remedy weird file structures

### PR DESCRIPTION
**Pull request by luke80**

### CODE REVIEW

**Comment by Gi60s** [comment]
I don't know how to resolve this merge conflict. Do you have any idea what's going on?

**Comment by luke80** [comment]
I'll take a look in a bit. It's probably because I moved files, then deleted them.

**Comment by luke80** [comment]
This should now merge.

**Comment by Gi60s** [comment]
Thanks, Luke.

**Comment by luke80** [comment]
You're welcome! Glad to help!

**Pull request merged**
